### ISSUE TITLE
How can I disable Perl::Tidy completely?

### ISSUE THREAD

**Issue by michaelherger** [vscode-perl/vscode-perl#11]
I'd like to disable Perl::Tidy. Tried to set it to an empty string, but that would still give me the console with a "TypeError: Bad argument" message whenever I save a file.

**Comment by henriiik** [comment]
Hello!

I have built a new version of the extension with your fix included. You can try it out by downloading it and installing it in vscode manually (https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

https://github.com/henriiik/vscode-perl/raw/master/vscode-perl-1.15.0.vsix

I will try it out for a week or so before releasing it.
