### ISSUE TITLE
Exclude Files/Folders

### ISSUE THREAD

**Issue by Mordef** [vscode-perl/vscode-perl#13]
I have a Project with over 50k files.
Dont need them in VSCode, so many Folders where exclude in explorer/search (search.exclude files.exclude)

The Generater looks like ignore the settings and try to create a ctags file with all files.
So the ctags file have entrys from excluded files.

Maybe u can add something like:
perl.ctagsignore = .ctagsignore

and add to options --exclude=@.ctagsignore

(Or build from search.exclude/files.exclude)

**Comment by henriiik** [comment]
Hello!

Unfortunately i don't have a lot of time to devote to this extension. But pull requests are welcome. :)

**Comment by ganralf** [comment]
@Mordef can you please check if [this PR](https://github.com/henriiik/vscode-perl/pull/22) solves your issue?

You can add --exclude=@.ctagsignore to the array of extra ctags parameters

**Comment by ngetahun** [comment]
I'm closing this issue since there's no response from @Mordef.
