### ISSUE TITLE
PerlTidy shall not enforce arbitrary rules

### ISSUE THREAD

**Issue by moltar** [vscode-perl/vscode-perl#14]
Arguably, PerlTidy should be a separate extension and not be part of this at all.

But if you want to keep it, please do not set arbitrary rules via CLI arguments:

https://github.com/henriiik/vscode-perl/blob/b66d23a7e0332e02bed081feae82a6e844fa0d16/src/format.ts#L27

Instead let users decide and provide their own `.perltidyrc` file.

Ideally, it should search for `.perltidyrc` starting at the dir closest to the file and down the dirs to the root and use that file.

E.g. look for files in this order:

```
~/dev/project/somedir/.perltidyrc
~/dev/project/.perltidyrc
~/dev/.perltidyrc
~/.perltidyrc
```

**Comment by moltar** [comment]
The last feature (search path) is supported directly by PerlTidy, when setting profile to:

`.../.perltidyrc` magic string, which is documented as:

> A pathname begins with three dots, e.g. ".../.perltidyrc", indicates that the file
> should be searched for starting in the current directory and working upwards.
> This makes it easier to have multiple projects each with their
> own .perltidyrc in their root directories.

So, arguable, this should be the default value for the profile option, and then let user override it however they want.

**Comment by henriiik** [comment]
Hello!

Unfortunately i don't have a lot of time to devote to this extension. But pull requests are welcome. :)

**Comment by forrcaho** [comment]
I just submitted a pull request which would move the perltidy args into the vscode user config. I don't know how it would interact with .perltidyrc, but at least it puts the arguments under the user's control.
