### ISSUE TITLE
Auto-complete subs that defined in packages.

### ISSUE THREAD

**Issue by MagicPro1994** [vscode-perl/vscode-perl#15]
Hi there,
Can you help me to how to have auto-completions for Subs or make this feature?
I can see the extension can see the Package but it seems not to have Subs auto-completions.

Thank you.

**Comment by henriiik** [comment]
Hello!

The extension should auto complete subs from packages that you have imported with `use` as long as all the files are in the same workspace.

**Comment by ngetahun** [comment]
@MagicPro1994 is the issue still there. I'm closing this issue but feel free if the issue still persists.
