### ISSUE TITLE
Support new Outline API extension

### ISSUE THREAD

**Issue by vphantom** [vscode-perl/vscode-perl#20]
Hello,

As of vscode 1.24, there's a new Outline feature on the left.  As I detailed in [vscode#51715](https://github.com/Microsoft/vscode/issues/51715), for Perl code we do get symbols and their line numbers, but they point to file `null` because `vscode-perl` isn't yet aware of this new API.

**Comment by DeeHants** [comment]
I can't get any outlining using the `vscode-perl` module.
I do however use [](url)
Note that there is another extension that provides some level of outlining
