### ISSUE TITLE
vscode-perl is not maintained

### ISSUE THREAD

**Issue by ngetahun** [vscode-perl/vscode-perl#23]
Hi @henriiik,
I saw that this extension isn't being actively maintained. Since I heavily rely on this extension for work, I'd like to help maintaining it or take it over from you.

**Comment by henriiik** [comment]
Hello!

That's great to hear! I have created an organization for the extension and invited you. :)

**Comment by ngetahun** [comment]
Hey @henriiik,
Thanks for adding me to the organization. I think we should establish a gitter/slack channel for communication and upcoming releases. What are your thoughts on this?

**Comment by ngetahun** [comment]
@henriiik can you close this issue?

**Comment by henriiik** [comment]
Hello! I have upgraded you to organization owner so you should be able to close it yourself. 🙂

**Comment by ngetahun** [comment]
Thanks :)

**Comment by kevlangdo** [comment]
I have started using Perl with VS code and have a vested interest in maintaining and supporting the extension. I would like to join the project as a maintainer or collaborator. Thanks
