### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by nflorin** [vscode-perl/vscode-perl#9]
When I save a Perl file, the text `Error: write EPIPE` appears in the Output window. The file appears to save correctly. The message goes away when I disable the plugin.

I'm on Windows 10. I have Perltidy installed, and it runs correctly from a plain cmd.exe. I tried changing the `perl.perltidy` setting, to no effect.

**Comment by henriiik** [comment]
sounds like it might be a problem with ctags rather than perltidy, is there no additional information?

**Comment by boeningc** [comment]
Same issue.

**Comment by SheikhThingsUp** [comment]
I was able to fix this installing ctags with chocolaty instead of installing it manually.
`choco install ctags`

**Comment by ngetahun** [comment]
I will be closing this issue since it seems stale, please reopen it if the problem resurfaces.
